pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://repo.spongepowered.org/maven' }
    }
    resolutionStrategy {
        eachPlugin {
            if (it.requested.id.id == 'net.minecraftforge.gradle') {
                it.useModule('net.minecraftforge.gradle:ForgeGradle:6.0.+')
            }
            if (it.requested.id.id == 'org.spongepowered.mixin') {
                it.useModule('org.spongepowered:mixingradle:0.7.+')
            }
        }
    }
}
