modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPL 3.0"

[[mods]]
modId="anticheat_screenshot"
version="1.1"
displayName="ACIvllas"
authors=""

[[dependencies."acivllas"]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies."acivllas"]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
