plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

group = 'com.pigeostudios.pwp'
version = '1.0.1'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                pwpwarfare {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = "GeckoLib"
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
    }
    maven {
        name = "TheIllusiveC4"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "henkelmax"
        url = "https://maven.maxhenkel.de/repository/public"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'

    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-1.20.1:4.4.9")
    implementation fg.deobf("top.theillusivec4.curios:curios-forge:5.14.1+1.20.1")
    implementation "de.maxhenkel.voicechat:voicechat-api:2.6.20"
}

jar {
    manifest {
        attributes([
                "Specification-Title": "pwpwarfare",
                "Specification-Vendor": "pigeostudios",
                "Specification-Version": "1",
                "Implementation-Title": project.name,
                "Implementation-Version": project.version,
                "Implementation-Vendor": "pigeostudios",
        ])
    }
}