modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="pwp_cosmetics"
version="1.0.0"
displayName="PWP Cosmetics"
credits="Pigeo Studios"
authors="Pigeo Studios"
description='''
Cosmetics system for PWP. Knife skins, weapon skins, uniforms, effects.
'''
side="CLIENT"
