plugins {
    id 'java'
    id 'application'
}

group = 'com.pwp'
version = '1.0.0'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:6.4.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.zaxxer:HikariCP:6.2.1'
    implementation 'com.mysql:mysql-connector-j:9.2.0'
    implementation 'ch.qos.logback:logback-classic:1.5.16'
    implementation 'org.slf4j:slf4j-api:2.0.16'
}

application {
    mainClass = 'com.pwp.core.CoreApplication'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.pwp.core.CoreApplication'
    }
}
