modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="pwp_lobby"
version="1.0.0"
displayName="PWP Lobby"
credits="Pigeo Studios"
authors="Pigeo Studios"
description='''
Lobby server mod for PWP. Player hub, map voting, server management.
'''
[[dependencies.pwp_lobby]]
    modId="pwpcore"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="SERVER"
