modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="explosionoverhaul"
version="0.2.3.0-forge"
displayName="Explosion Overhaul: A new level of destruction"
displayURL="https://vinlanx.github.io/vinlanx/"
logoFile="logo.png"
authors="Vinlanx"
credits="Check CREDITS.txt file for details."
description='''
This mod completely rethinks explosions in Minecraft, making them incredibly realistic and dynamic. Enjoy unique explosion sounds that change depending on the distance and environment, tangible shockwaves and concussions, as well as realistic visual effects, including plasma sparks and fire clouds. Experience the true destructive power of explosions like never before
'''
mixinConfigs = ["explosionoverhaul.mixins.json"]



[[dependencies.explosionoverhaul]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"


[[dependencies.explosionoverhaul]]
modId="cloth_config"
mandatory=true 
versionRange="[11.1.106,)"
ordering="NONE"
side="CLIENT" 

[[dependencies.explosionoverhaul]]
modId="geckolib"
mandatory=true
versionRange="[4.0,)"
ordering="NONE"
side="BOTH"
