modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="pwp_core_client"
version="1.0.1"
displayName="PWP Core Client"
credits="Pigeo Studios"
authors="Pigeo Studios"
description='''
Core client mod for PWP. Custom main menu, loading screen, and client utilities.
'''

[[mixins]]
config="pwp_core_client.mixins.json"

[[dependencies.pwp_core_client]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.pwp_core_client]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.pwp_core_client]]
    modId="pwpcore"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="SERVER"