modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="pwp_core_client"
version="1.0.0"
displayName="PWP Core Client"
credits="Pigeo Studios"
authors="Pigeo Studios"
description='''
Core client mod for PWP. Connects to PWP Core Service for player data.
'''
