plugins {
    id 'java'
}

group = 'net.pwp.early'
version = '0.0.1'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
    maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }
    maven { name = 'Mojang'; url = 'https://libraries.minecraft.net/' }
}

dependencies {
    compileOnly 'net.minecraftforge:fmlloader:1.20.1-47.3.0'
    compileOnly 'org.lwjgl:lwjgl:3.3.1'
    compileOnly 'org.lwjgl:lwjgl-glfw:3.3.1'
    compileOnly 'org.lwjgl:lwjgl-opengl:3.3.1'
}

jar {
    archiveBaseName = 'pwp-early-display'
    archiveVersion = '0.0.1'
    manifest {
        attributes 'Specification-Title': 'PWP Early Display'
    }
}
