package com.pwp.core;

import com.pwp.core.api.*;
import com.pwp.core.auth.AuthMiddleware;
import com.pwp.core.db.DatabaseManager;
import io.javalin.Javalin;
import org.slf4j.Logger;
import java.sql.Statement;
import org.slf4j.LoggerFactory;

import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class CoreApplication {

    private static final Logger log = LoggerFactory.getLogger(CoreApplication.class);

    public static Config config;

    public static String projectVersion = "dev";
    public static String projectCommit = "unknown";
    public static String projectDate = "";
    public static String projectChangelog = "";

    public static void main(String[] args) {
        log.info("Starting PWP Core Service...");

        loadConfig(args.length > 0 ? args[0] : "config.json");
        loadVersion();

        DatabaseManager.init(config.database);

        // Cleanup просроченных токенов при старте
        cleanupExpiredTokens();
        // И раз в час
        java.util.concurrent.Executors.newSingleThreadScheduledExecutor()
            .scheduleAtFixedRate(() -> cleanupExpiredTokens(), 1, 1, java.util.concurrent.TimeUnit.HOURS);

        int port = config.server.port;
        Javalin app = Javalin.create(cfg -> {
            cfg.showJavalinBanner = false;
            com.pwp.core.api.GsonMapper.apply(cfg);
        });

        app.before("/api/*", ctx -> AuthMiddleware.handle(ctx, config.api));

        app.get("/api/v1/health", ctx -> ctx.json(java.util.Map.of("status", "ok")));
        app.get("/api/v1/version", ctx -> ctx.json(java.util.Map.of(
            "launcher", projectVersion,
            "server", projectVersion,
            "manifest", "1",
            "maintenance", false
        )));

        new PlayerController(app, config);
        new CurrencyController(app);
        new XpController(app);
        new CosmeticsController(app);
        new MatchController(app);
        new ShopController(app);
        new DonationController(app);
        new SkinController(app);
        new SkinV2Controller(app);
        new CaseController(app);
        new RankController(app);
        new RewardController(app);
        new KitController(app);
        new FactionVehicleController(app);
        new VoiceMuteController(app);
        new AuthController(app, config);
        new AdminController(app);
        new NetworkController(app);
        new LauncherController(app);
        new AuthLibController(app);
        new HWIDBanController(app);
        new MatchPolicyController(app);
        new SecurityController(app, config);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            log.info("Shutting down Core Service...");
            app.stop();
            DatabaseManager.shutdown();
        }));

        app.start(port);
        log.info("PWP Core Service running on port {}", port);
    }

    private static void loadVersion() {
        // try files first (generated by gradle writeVersionFiles)
        try { projectVersion = Files.readString(Paths.get("version.txt")).trim(); } catch (Exception ignored) {}
        try { projectCommit = Files.readString(Paths.get("commit.txt")).trim(); } catch (Exception ignored) {}
        try {
            List<String> lines = Files.readAllLines(Paths.get("changelog.txt"));
            projectChangelog = String.join("\n", lines);
            if (!lines.isEmpty()) projectDate = lines.get(0).replaceAll(".*\\(|\\).*", "").trim();
        } catch (Exception ignored) {}
        // fallback: read from git directly if files are missing
        if (projectVersion.equals("dev")) {
            try { projectVersion = exec("git describe --tags --always 2>nul").trim(); } catch (Exception ignored) {}
        }
        if (projectCommit.equals("unknown")) {
            try { projectCommit = exec("git rev-parse --short HEAD 2>nul").trim(); } catch (Exception ignored) {}
        }
        if (projectChangelog.isEmpty()) {
            try {
                projectChangelog = exec("git log --oneline --no-decorate -10 2>nul").trim();
                if (!projectChangelog.isEmpty()) {
                    projectDate = projectChangelog.lines().findFirst().orElse("").replaceAll(".*\\(|\\).*", "").trim();
                }
            } catch (Exception ignored) {}
        }
        log.info("Version: {} (commit {})", projectVersion, projectCommit);
    }

    private static String exec(String cmd) throws Exception {
        var proc = Runtime.getRuntime().exec(cmd, null, Paths.get(".").toAbsolutePath().getParent().toFile());
        try (var reader = new java.io.BufferedReader(new java.io.InputStreamReader(proc.getInputStream()))) {
            return reader.readLine();
        }
    }

    private static void loadConfig(String path) {
        // Search order: explicit path -> cwd -> next to the JAR (../.. from build/libs)
        List<java.nio.file.Path> candidates = new java.util.ArrayList<>();
        try { candidates.add(Paths.get(path)); } catch (Exception ignored) {}
        try {
            java.io.File jar = new java.io.File(
                CoreApplication.class.getProtectionDomain().getCodeSource().getLocation().toURI());
            java.nio.file.Path dir = jar.isDirectory() ? jar.toPath() : jar.toPath().getParent();
            candidates.add(dir.resolve("config.json"));
            candidates.add(dir.getParent().resolve("config.json"));
            candidates.add(dir.getParent().getParent().resolve("config.json"));
        } catch (Exception ignored) {}

        for (java.nio.file.Path c : candidates) {
            if (!Files.exists(c)) continue;
            try (FileReader reader = new FileReader(c.toFile())) {
                config = new com.google.gson.Gson().fromJson(reader, Config.class);
                log.info("Loaded config from {}", c);
                return;
            } catch (Exception e) {
                log.warn("Could not parse config '{}': {}", c, e.getMessage());
            }
        }
        log.warn("Could not load config file '{}', using defaults", path);
        config = new Config();
    }

    public static class Config {
        public ServerConfig server = new ServerConfig();
        public DatabaseConfig database = new DatabaseConfig();
        public ApiConfig api = new ApiConfig();
        public LoggingConfig logging = new LoggingConfig();
        public LauncherConfig launcher = new LauncherConfig();

    }

    public static class LauncherConfig {
        public String filesDir = "C:/Users/maska/OneDrive/Desktop/SERVER";
        public String downloadBaseUrl = "/launcher/files";
    }

    public static class ServerConfig {
        public int port = 8080;
        public String host = "0.0.0.0";
    }

    public static class DatabaseConfig {
        public String host = "127.0.0.1";
        public int port = 3306;
        public String name = "pwp_core";
        public String user = "root";
        public String password = "";
        public int poolSize = 10;
        public long maxLifetimeMs = 1800000;
    }

    private static void cleanupExpiredTokens() {
        try (java.sql.Connection c = DatabaseManager.getConnection();
             var ps = c.prepareStatement("DELETE FROM auth_tokens WHERE expires_at < NOW()")) {
            int deleted = ps.executeUpdate();
            if (deleted > 0) log.info("Cleaned up {} expired auth tokens", deleted);
        } catch (Exception e) {
            log.warn("Failed to cleanup expired auth tokens: {}", e.getMessage());
        }
        try (java.sql.Connection c = DatabaseManager.getConnection();
             var ps = c.prepareStatement("DELETE FROM sessions WHERE expires_at < NOW()")) {
            int deleted = ps.executeUpdate();
            if (deleted > 0) log.info("Cleaned up {} expired sessions", deleted);
        } catch (Exception e) {
            log.warn("Failed to cleanup expired sessions: {}", e.getMessage());
        }
    }

    public static class ApiConfig {
        public String[] keys = {};
        public int rateLimitPerMinute = 500;
        public int rateLimitPerMinuteAdmin = 10;
        public String adminTelegramIds = "";
        public String[] rateLimitBypassKeys = {};
    }

    public static class LoggingConfig {
        public String level = "INFO";
        public String file = "logs/core-service.log";
    }
}
